import { Question } from '@/store/quiz';

export const sampleQuestions: Question[] = [
  {
    id: '1',
    type: 'multiple',
    title: 'What do you want to improve the most in your English?',
    options: [
      'Speaking with confidence',
      'Pronunciation and clarity',
      'Expanding my vocabulary',
      'Using correct grammar',
      'Understanding native speakers',
      'Writing fluently',
    ],
    required: true,
  },
  {
    id: '2',
    type: 'single',
    title: 'How often do you speak English in your daily life?',
    options: ['Every day', 'A few per week', 'A few per month', 'None'],
    required: true,
  },
  {
    id: '3',
    type: 'single',
    title: 'What is your main goal in learning English?',
    options: [
      'Advance my career',
      'Support my education',
      'Study Abroad',
      'Living Abroad',
      'Travel Easily',
      'Personal Development',
      'Connect with people',
    ],
    required: true,
  },
  {
    id: '4',
    type: 'multiple',
    title: 'How did you try to learn?',
    options: [
      'Mobile app',
      'Online teacher',
      'School',
      'Language courses',
      'Self education',
      'Abroad',
    ],
    required: true,
  },
  {
    id: '5',
    type: 'single',
    title: 'How would you describe your previous English learning experiences?',
    options: [
      "It was too expensive, and I didn't want to spend that much money",
      "I struggled to dedicate time and couldn't continue",
      "I didn't want to practice speaking in front of others",
      "There wasn't a personalized program for me",
      "My schedule didn't match with my teacher's",
      'I made progress, but I want to improve further',
    ],
    required: true,
  },
  {
    id: '6',
    type: 'multiple',
    title: 'What usually stops you from speaking English?',
    options: [
      'I freeze or panic',
      "I can't find the right words",
      "My accent isn't clear",
      'Grammar mistakes',
      "I can't reply quickly",
      'None of the above',
    ],
    required: true,
  },
  {
    id: '7',
    type: 'multiple',
    title: 'How do you use English in your daily life?',
    options: [
      'Using English at work or school',
      'Reading English news or books',
      'Watching shows or YouTube',
      'Listening to English music or podcasts',
      'Chatting with English speakers',
      'I rarely use English',
    ],
    required: true,
  },
  {
    id: '8',
    type: 'single',
    title: 'What field do you work in?',
    options: [
      'Tech / Engineering',
      'Business / Finance',
      'Student / Education',
      'Creative / Media',
      'Skilled jobs / Services',
      'Marketing / Sales',
      'Healthcare / Science',
      'Currently not working',
      'Other',
    ],
    required: true,
  },
  {
    id: '9',
    type: 'single',
    title: 'How old are you?',
    options: [
      'Under 18',
      '18–24',
      '25–34',
      '35–44',
      '45–54',
      '55–64',
      '65+',
      'Prefer not to say',
    ],
    required: true,
  },
  {
    id: '10',
    type: 'single',
    title: 'Select your gender.',
    options: ['Male', 'Female', 'Prefer not to say'],
    required: true,
  },
  {
    id: '11',
    type: 'multiple',
    title: 'How are you currently learning English?',
    options: [
      'Language courses or tutors',
      'Learning apps',
      'Videos or movies',
      'Podcasts or audiobooks',
      'Speaking with others',
      'Not learning right now',
    ],
    required: true,
  },
  {
    id: '12',
    type: 'multiple',
    title: 'What are the biggest challenges for you in learning English?',
    options: [
      "It's hard to find time",
      "It's hard to stay motivated",
      'I feel nervous when speaking',
      'Lack of opportunities to speak',
      'I forget what I learn',
      'English feels too hard',
      "No challenges, I'm doing great!",
    ],
    required: true,
  },
  {
    id: '13',
    type: 'single',
    title: 'What is your current English level?',
    options: [
      'Beginner (I can buy things & order food)',
      'Intermediate (I can have simple conversations)',
      'Upper-Intermediate (I can explain ideas and join discussions on various topics)',
      'Advanced (I speak confidently at work and socially)',
    ],
    required: true,
  },
  {
    id: '14',
    type: 'multiple',
    title:
      'What are your hobbies and interests? This helps Al pick the topics you like for your lessons. Select 3-5 options.',
    options: [
      'Science',
      'Literature',
      'Politics',
      'Psychology',
      'Philosophy',
      'Business',
      'News',
      'Finance',
      'Marketing',
      'Pop Culture',
      'Cooking',
      'Pets',
      'Food',
      'Travel',
      'Shopping',
      'Movies',
      'Technology',
      'Music',
      'Health & Fitness',
      'Fashion',
      'Culture',
      'Career',
      'History',
      'Social Media',
      'Art & Creativity',
    ],
    required: true,
    redirect: '/voice',
  },
];
